In [6]:
#1. Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements

import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))



[0. 0. 0. 0. 0.]


In [8]:
#. Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(2, 3))


[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:

#3. Write a function generate_range_array(start, stop, step) to create a ranged NumPy array


def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))


[1 3 5 7 9]


In [12]:
#4. Design a function generate_linear_space(start, stop, num) for equally spaced values.

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(1, 10, 5))


[ 1.    3.25  5.5   7.75 10.  ]


In [14]:
#5. Create a function create_identity_matrix(n) using numpy.eye.

def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#6. Write a function that converts a Python list into a NumPy array

def list_to_numpy_array(py_list):
    return np.array(py_list)

my_list = [1, 2, 3, 4, 5]
print(list_to_numpy_array(my_list))


[1 2 3 4 5]


In [18]:
#17. Create a NumPy array and use numpy.view() to create a new view with the same data
arr = np.array([1, 2, 3, 4, 5])

new_view = arr.view()

print("Original Array:", arr)
print("New View:", new_view)



Original Array: [1 2 3 4 5]
New View: [1 2 3 4 5]
