In [4]:
#36. Add scalar 5 to every element of an array using broadcasting.

import numpy as np
arr=np.array([1,2,3,4,5,6])
for i in arr:
    print(i+5,end=" ")


6 7 8 9 10 11 

In [6]:
#using broadcasting
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
result = arr + 5
print(result)


[ 6  7  8  9 10 11]


In [8]:
#37. Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])

B = np.array([[2, 3, 4]])

# Transpose B to make it (3,1) so it matches rows
result = A * B.T

print(result)





[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [12]:
#38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting.
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10,11,12]])

B = np.array([[10, 20, 30]])

result = A + B

print(result)



[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [16]:
import numpy as np

arr1 = np.array([[1],
                 [2],
                 [3]])  # Shape (3,1)

arr2 = np.array([[10, 20, 30]])  # Shape (1,3)

res = arr1 + arr2
print(res)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [22]:
#40. Handle shape incompatibility during multiplication between (2, 3) and (2, 2) arrays

import numpy as np

arr1 = np.array([[1,2,3],
                 [4,5,6]])    




arr2 = np.array([[1,2,3],
                 [4,5,6]])    

res = arr1 * arr2
print(res)



[[ 1  4  9]
 [16 25 36]]


In [32]:
#column wise mean of 2d array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

column_mean = np.mean(arr, axis=0)
print("Column-wise mean:", column_mean)


Column-wise mean: [4. 5. 6.]


In [34]:
#max vale in each row
row_max = np.max(arr, axis=1)
print("Row-wise maximum:", row_max)


Row-wise maximum: [3 6 9]


In [36]:
#indices of max value in each column

col_max_indices = np.argmax(arr, axis=0)
print("Indices of column-wise max:", col_max_indices)



Indices of column-wise max: [2 2 2]


In [38]:
#custom function to move sum along row

def moving_sum(row):
    return np.convolve(row, np.ones(2, dtype=int), 'valid')

result = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print("Moving sum along rows:\n", result)


Moving sum along rows:
 [[ 3  5]
 [ 9 11]
 [15 17]]


In [42]:
#45. Check if all elements in each column are even

all_even = np.all(arr % 2 == 0, axis=0)
print("Are all elements even column-wise?:", all_even)


Are all elements even column-wise?: [False False False]
