In [22]:
#18. Write a function to concatenate two NumPy arrays along a specified axis.
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

result = concatenate_arrays(arr1, arr2)
print(result)


[1 2 3 4 5 6 7 8]


In [28]:
#19. Concatenate two arrays with different shapes horizontally using numpy.concatenate

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)


[[1 2 5]
 [3 4 6]]


In [30]:
#20. Vertically stack multiple arrays from a list using numpy.vstack
import numpy as np

arrays_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

result = np.vstack(arrays_list)

print(result)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
