In [4]:
#26. Access the 3rd element from the given NumPy array.
import numpy as np
arr=np.array([9,5,2,6,7,2])
arr[2]


2

In [18]:
#27. Retrieve the element at index (1, 2) from a 2D array.

array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d[1,2])


7


In [20]:
#28. Extract elements greater than 5 using boolean indexing.

import numpy as np

arr = np.array([2, 6, 3, 8, 5, 9])
result = arr[arr > 5]
print(result)


[6 8 9]


In [22]:
#29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.
result = arr[2:6]
print(result)


[3 8 5 9]


In [24]:
#30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array


import numpy as np

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

result = array_2d[:, 1:3]
print(result)


[[2 3]
 [5 6]]


In [26]:
#31. Extract elements based on indices from a 2D array.

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Extract elements at positions: (0,1), (1,2), (2,0)
rows = np.array([0, 1, 2])
cols = np.array([1, 2, 0])

result = arr[rows, cols]
print(result)




[20 60 70]


In [28]:
#32. Filter elements greater than a threshold using boolean indexing.
arr = np.array([5, 10, 15, 20, 25])

result = arr[arr > 15]
print(result)


[20 25]


In [30]:
#33. Extract specific elements from a 3D array using separate index arrays.
arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

# Example: Extract elements at positions (0,1,1), (1,0,0)
x = np.array([0, 1])   # First dimension
y = np.array([1, 0])   # Second dimension
z = np.array([1, 0])   # Third dimension

result = arr[x, y, z]
print(result)


[4 5]


In [32]:

#34. Return elements satisfying two boolean conditions.
arr = np.array([2, 5, 8, 11, 14, 17])

# Example: Elements > 5 and < 15
result = arr[(arr > 5) & (arr < 15)]
print(result)


[ 8 11 14]


In [34]:

#35. Extract elements from a 2D array using separate row and column index arrays
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

rows = np.array([0, 1, 2])
cols = np.array([2, 0, 1])

result = arr[rows, cols]
print(result)


[30 40 80]
