In [4]:
## 46. Reshape a given array into dimensions m x n
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Reshaping into 2x3
print("46. Reshaped Array:\n", reshaped_arr)

46. Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
# 47. Return a flattened version of a given matrix
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
flattened_arr = arr2.flatten()
print("47. Flattened Array:\n", flattened_arr)


47. Flattened Array:
 [1 2 3 4 5 6]


In [8]:
# 48. Concatenate two arrays along a specified axis
arr3 = np.array([[1, 2],
                 [3, 4]])
arr4 = np.array([[5, 6],
                 [7, 8]])


concat_axis0 = np.concatenate((arr3, arr4), axis=0)
print(" Concatenated along axis 0 (rows):\n", concat_axis0)


concat_axis1 = np.concatenate((arr3, arr4), axis=1)
print("Concatenated along axis 1 (columns):\n", concat_axis1)

 Concatenated along axis 0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1 (columns):
 [[1 2 5 6]
 [3 4 7 8]]


In [10]:
# 49. Split an array into sub-arrays along a specified axis
arr5 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

# Horizontal split (split columns)
hsplit_arr = np.hsplit(arr5, 2)
print(" Horizontal Split:")
for part in hsplit_arr:
    print(part)

# Vertical split (split rows)
vsplit_arr = np.vsplit(arr5, 2)
print("Vertical Split:")
for part in vsplit_arr:
    print(part)

 Horizontal Split:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
49. Vertical Split:
[[1 2 3 4]]
[[5 6 7 8]]


In [12]:
# 50. Insert and delete elements at specified indices from an array
arr6 = np.array([1, 2, 3, 4, 5])

# Insert 99 at index 2
arr_insert = np.insert(arr6, 2, 99)
print("50. After Insert at index 2:\n", arr_insert)

# Delete element at index 3
arr_delete = np.delete(arr6, 3)
print("50. After Delete at index 3:\n", arr_delete)

50. After Insert at index 2:
 [ 1  2 99  3  4  5]
50. After Delete at index 3:
 [1 2 3 5]


In [22]:
import numpy as np

# 51. Perform element-wise addition between two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

add_result = arr1 + arr2
print(" Element-wise Addition:\n", add_result)



 Element-wise Addition:
 [5 7 9]


In [18]:
# 52. Perform element-wise subtraction: subtract arr2 from arr1
sub_result = arr1 - arr2
print("Element-wise Subtraction (arr1 - arr2):\n", sub_result)


Element-wise Subtraction (arr1 - arr2):
 [-3 -3 -3]


In [20]:
## 53. Perform element-wise multiplication
mul_result = arr1 * arr2
print("Element-wise Multiplication:\n", mul_result)

Element-wise Multiplication:
 [ 4 10 18]


In [28]:
# 54. Divide elements of arr1 by arr2 element-wise
div_result = arr1 / arr2
print("Element-wise Division (arr1 / arr2):\n", div_result)

Element-wise Division (arr1 / arr2):
 [0.25 0.4  0.5 ]


In [30]:
# 55. Perform element-wise exponentiation: arr1 ** arr2
exp_result = arr1 ** arr2
print("Element-wise Exponentiation (arr1 ** arr2):\n", exp_result)

Element-wise Exponentiation (arr1 ** arr2):
 [  1  32 729]
