In [4]:
import numpy as np

# 66. Find index of a specific element in an array
arr = np.array([10, 20, 30, 40, 50])
element = 30
index = np.where(arr == element)
print("66. Index of element 30:\n", index)



66. Index of element 30:
 (array([2], dtype=int64),)


In [6]:


# 67. Sort a random array in ascending order
arr2 = np.random.randint(1, 101, 10)  # Random array of size 10, values between 1 and 100
sorted_arr = np.sort(arr2)
print("67. Original Random Array:\n", arr2)
print("67. Sorted Array (Ascending):\n", sorted_arr)



67. Original Random Array:
 [49 77  2 40 81 88  5 81 17 32]
67. Sorted Array (Ascending):
 [ 2  5 17 32 40 49 77 81 81 88]


In [12]:


# 68. Filter elements greater than 20
arr3 = np.array([5, 15, 25, 35, 10, 45])
filtered_greater_20 = arr3[arr3 > 20]
print("68. Elements greater than 20:\n", filtered_greater_20)



68. Elements greater than 20:
 [25 35 45]


In [14]:
# 69. Filter elements divisible by 3
arr4 = np.array([3, 6, 9, 10, 15, 20, 25])
divisible_by_3 = arr4[arr4 % 3 == 0]
print("69. Elements divisible by 3:\n", divisible_by_3)





69. Elements divisible by 3:
 [ 3  6  9 15]


In [16]:

# 70. Filter elements between 20 and 40 (inclusive)
arr5 = np.array([10, 20, 25, 30, 40, 45, 50])
between_20_and_40 = arr5[(arr5 >= 20) & (arr5 <= 40)]
print("70. Elements between 20 and 40 (inclusive):\n", between_20_and_40)


70. Elements between 20 and 40 (inclusive):
 [20 25 30 40]


In [18]:
# 71. Check byte order of a NumPy array using dtype.byteorder
arr = np.array([1, 2, 3], dtype=np.int16)
print("Byte Order of array:")
print(arr.dtype.byteorder)

Byte Order of array:
=


In [20]:
# 72. Perform in-place byte swapping using byteswap()
print(" Original Array before byteswap:\n", arr)

# In-place byte swap
arr.byteswap(inplace=True)
print("Array after in-place byteswap:\n", arr)


 Original Array before byteswap:
 [1 2 3]
Array after in-place byteswap:
 [256 512 768]
