In [4]:
import numpy as np

# 56. Count occurrences of a substring in a string array
arr = np.array(['apple', 'banana', 'apple pie', 'pineapple'])
substring_count = np.char.count(arr, 'apple')
print("Count of 'apple' in each element:\n", substring_count)


Count of 'apple' in each element:
 [1 0 1 1]


In [10]:
# 57. Extract uppercase characters from a string array
arr2 = np.array(['Hello', 'WORLD', 'Python3'])
uppercase_chars = np.array([''.join([ch for ch in word if ch.isupper()]) for word in arr2])
print("Uppercase characters from each element:\n", uppercase_chars)


Uppercase characters from each element:
 ['H' 'WORLD' 'P']


In [12]:
# 58. Replace substring occurrences with another string in a string array
arr3 = np.array(['I like Python', 'Python is fun', 'Python Programming'])
replaced_arr = np.char.replace(arr3, 'Python', 'NumPy')
print("After replacing 'Python' with 'NumPy':\n", replaced_arr)

After replacing 'Python' with 'NumPy':
 ['I like NumPy' 'NumPy is fun' 'NumPy Programming']


In [16]:
# 59. Concatenate strings in a NumPy array element-wise
arr4 = np.array(['Data', 'Num', 'Py'])
arr5 = np.array(['Science', 'Py', 'thon'])
concatenated = np.char.add(arr4, arr5)
print("Element-wise Concatenation:\n", concatenated)

Element-wise Concatenation:
 ['DataScience' 'NumPy' 'Python']


In [18]:
# 60. Find the length of the longest string in a string array
arr6 = np.array(['apple', 'banana', 'cherry', 'watermelon'])
lengths = np.char.str_len(arr6)
max_length = np.max(lengths)
print(" Length of the longest string:\n", max_length)

 Length of the longest string:
 10


In [20]:
# 61. Generate 100 random integers (1–1000) and compute mean, median, variance, and std deviation
arr1 = np.random.randint(1, 1001, 100)
mean_val = np.mean(arr1)
median_val = np.median(arr1)
variance_val = np.var(arr1)
std_dev_val = np.std(arr1)

print("Mean:", mean_val)
print("Median:", median_val)
print("Variance:", variance_val)
print("Standard Deviation:", std_dev_val)

Mean: 483.43
Median: 445.5
Variance: 89451.70509999999
Standard Deviation: 299.0847791178949


In [22]:
# 62. Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles
arr2 = np.random.randint(1, 101, 50)
percentile_25 = np.percentile(arr2, 25)
percentile_75 = np.percentile(arr2, 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


25th Percentile: 31.75
75th Percentile: 75.0


In [24]:
# 63. Compute correlation coefficient between two arrays using np.corrcoef
x = np.random.randint(1, 100, 10)
y = np.random.randint(1, 100, 10)

correlation_matrix = np.corrcoef(x, y)
print("Correlation Coefficient Matrix:\n", correlation_matrix)


Correlation Coefficient Matrix:
 [[ 1.         -0.17954937]
 [-0.17954937  1.        ]]


In [26]:
# 64. Perform matrix multiplication using np.dot
mat1 = np.array([[1, 2],
                 [3, 4]])

mat2 = np.array([[5, 6],
                 [7, 8]])

matrix_multiplication = np.dot(mat1, mat2)
print(" Matrix Multiplication Result:\n", matrix_multiplication)


 Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [30]:
 #65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers
arr3 = np.random.randint(1, 101, 50)

percentile_10 = np.percentile(arr3, 10)
percentile_50 = np.percentile(arr3, 50)  # Median
percentile_90 = np.percentile(arr3, 90)

quartiles = np.percentile(arr3, [25, 50, 75])  # Q1, Q2, Q3

print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("Quartiles (Q1, Q2, Q3):", quartiles)

10th Percentile: 7.0
50th Percentile (Median): 47.5
90th Percentile: 84.2
Quartiles (Q1, Q2, Q3): [25.5 47.5 71.5]
